### ISSUE TITLE
URL update

### ISSUE THREAD

**Issue by revenantal** [nullx27/conduit#1]
Looks like CCP did a fairly silent change of the ESI url readable here, https://forums.eveonline.com/t/esi-base-url-update/63210 .

Seems they also moved to AWS from Google Cloud and ESI is all kinds of borked. When stuff stops being so borked might as well update the url.

**Comment by necrotex** [comment]
Yea, I noticed :( I made the base uri configurable so if ccp tries this stunt again everybody can change the uri in on their own, without waiting for me to update the lib :)
