### ISSUE TITLE
Conflict with another vendor

### ISSUE THREAD

**Issue by userbig** [nullx27/conduit#2]
Your conduit have some compatibility issue with irazasyed/telegram-bot-sdk. And i dont know why.

**Comment by necrotex** [comment]
Hey, can you post the composer error message in here?

**Comment by userbig** [comment]
Ops. That issue happened only with EASI, my bad. I don't have any composer errors, but telegram SDK won't get any updates, only 'false'
```

>>> Telegram::getUpdates()
=> [
     Telegram\Bot\Objects\Update {#2880
       all: [
         false,
       ],
     },
     Telegram\Bot\Objects\Update {#2883
       all: [
         false,
       ],
     },
     Telegram\Bot\Objects\Update {#2870
       all: [
         false,
       ],
     },
   ]

```

**Comment by necrotex** [comment]
Yea, easi is dead.  Does this happen with conduit too?
